### ISSUE TITLE
hỏi file ./script_build.sh

### ISSUE THREAD

**Issue by fulloption1998** [undertheseanlp/chatbot#19]
dạ cho em hỏi sao em làm để chạy được Bước 2: Build chatbot vậy ạ . em kiếm file ./script_build.sh hoài mà không ra. Mong anh/chị giúp đỡ cho sinh viên như em ạ!

**Comment by rain1024** [comment]
Sorry em vì doc hướng dẫn cũ chưa chính xác, anh đã cập nhật hướng dẫn rồi em nhé

**Comment by fulloption1998** [comment]
anh có thể hưởng dẫn cho em cách để tải dữ liệu chatbot lên server ở (Bước 2: Build chatbot) được không anh! em làm hoài mà vẫn không ra được. Khi chạy (Bước 3: Bật web server) thì bot không có dữ liệu để trả lời. Mong nhận được sự hỗ trợ từ từ a!

**Comment by rain1024** [comment]
@fulloption1998 Lạ nhỉ, anh vẫn build bình thường mà. Để anh check lại xem nhé

**Comment by fulloption1998** [comment]
dạ có gì anh check lại giúp em nhé ! em cảm ơn anh !

**Comment by rain1024** [comment]
Anh đã check lại source code và update một vài thành phần còn thiếu rồi em nhé.

Em thử lại nhé :D

**Comment by fulloption1998** [comment]
Dạ em cảm ơn anh ! em đã thử lại và đã chạy được rồi nha a !
