### ISSUE TITLE
Vấn đề về dấu câu của chatbot

### ISSUE THREAD

**Issue by pake2070** [undertheseanlp/chatbot#25]
Em là người mới trong lĩnh vực này, em thấy trên diễn đàn của Rasa anh chị có đề cập đến chatbot này, cho em hỏi là trước khi cho vào model để train thì dấu câu anh/chị xử lý như thế nào ạ ? Em cám ơn rất nhiều.

**Comment by rain1024** [comment]
Vấn đề này bạn hỏi trên Rasa thì hợp lý hơn.

Hiện tại thì mình chưa xử lý dấu câu đối với các câu đầu vào bạn nhé.
