### ISSUE TITLE
Sử dụng Chatscript

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/chatbot#3]
Chatscript là ngôn ngữ lập trình chatbot khá mạnh. Nên chuyển từ rivescript sang chatscript

Các thông tin thêm:

* [Trang github chatscript](https://github.com/bwilcox-1234/ChatScript)
* [Hướng dẫn xây dựng chatbot cơ bản](https://medium.freecodecamp.org/chatscript-for-beginners-chatbots-developers-c58bb591da8)

**Comment by hothanhluan** [comment]
#1 Đã cài đặt và chạy demo chatscript trên Ubuntu

**Comment by rain1024** [comment]
Cho xin mấy cái ảnh demo xem nào?

**Comment by hothanhluan** [comment]
Link ảnh demo : 
[https://drive.google.com/open?id=154aoXo6M3kfNzXxOWhed41uE4DhH0PKv](url)
[https://drive.google.com/open?id=1xSpwKsW-_4Sq5sZbYEInqGRbF4Cm1d_4](url)

**Comment by hothanhluan** [comment]
![screenshot from 2018-10-26 07-46-17](https://user-images.githubusercontent.com/13777934/47598732-d120a980-d9ca-11e8-82a9-6f704637e35a.png)
![screenshot from 2018-10-26 07-47-34](https://user-images.githubusercontent.com/13777934/47598735-d4b43080-d9ca-11e8-8172-b8d2f79f1100.png)
